---
title: '200408'
author: "yung-yu"
date: "2020/4/14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###選取元素

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```



[臺南市運動地圖](https://data.gov.tw/dataset/6217)
```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap

length(tainanSportsMap)
```

```{r}
tainanSportsMap[1]
tainanSportsMap[1076]
```

###用名字選

```{r}
# 有多少名字可選：
names(listExample)
```

```{r}
listExample$student
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```

```{r}
str(listExample)
```

```{r}
str(listExample$`學期`)
```

其實也可以用[["名字"]]來選，只是名字要以字串「值」的方式來寫，也就是要用引號一對"…", 不用反頓點一對`…`。

```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]] # 小心不是反頓點喔。
listExample$`學期`
```

```{r}
Student<-"student"
listExample[["student"]]
```


[新北市各區衛生所之門診時間及疫苗種類彙整表](https://data.gov.tw/dataset/26610#r1)
```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
```

```{r}
str(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
names(newTaipeiCityVaccine)
```

```{r}
str(newTaipeiCityVaccine[[1]])
str(newTaipeiCityVaccine$success)
str(newTaipeiCityVaccine[["success"]])

str(newTaipeiCityVaccine[[2]], max.level = 1)
str(newTaipeiCityVaccine$result, max.level = 1)
str(newTaipeiCityVaccine[["sresult"]], max.level = 1)
```


###選「多個元素」

####用位置選[c(...)]

```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,2,1)] # 產生重新排列效果
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

str(listExample[c(1,2)], max.level=1)
str(listExample[c(2,1)], max.level=1)
```


任選數筆tainanSportsMap的運動地點。
```{r}
str(tainanSportsMap, max.level = 1)
str(tainanSportsMap[c(1,382,1076)], max.level = 1)
```


### 用名字選[c("name1","name2",...)]

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c("學期")]
listExample[c("student","學期")]
listExample[c("學期","student")]
```

臺北市夜市資料（來自臺北市食材登錄平台食材來源資訊）：(https://data.taipei/#/dataset/detail?id=8a569b5b-0cb1-4c7f-a064-780b3301354c)

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

###用「要/不要」邏輯向量選[c(T,T,F,...)]

```{r}
vectorExample
vectorExample[c(T,T,F)] # 要，要，不要
```

